

services:
  mysql:
    image: mysql:8.0
    container_name: enc_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: enc_poc
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  vault:
    image: hashicorp/vault:1.15
    container_name: enc_vault
    restart: unless-stopped
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    command: "server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200"

  api:
    build: ./app
    container_name: enc_api
    restart: unless-stopped
    depends_on:
      - mysql
      - vault
    environment:
      # DB
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: enc_poc
      # Vault
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
      VAULT_TRANSIT_KEY: pii-master
    ports:
      - "8000:8000"

  adminer:
    image: adminer:4
    container_name: enc_adminer
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:
